import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { getTableName } from 'drizzle-orm';
import { getTableConfig } from 'drizzle-orm/pg-core';
import { schemaTables } from '../packages/infrastructure-db/src/schema.js';

const outputPath = resolve('docs/domain/data-dictionary.md');
const lines = [
  '---',
  'purpose: Report the PostgreSQL schema generated from Drizzle table definitions.',
  'audience: Owner, contributors, operators, and coding agents.',
  'authoritative-for: Generated database column and relationship documentation; schema source and migrations remain authoritative.',
  'update-triggers: Drizzle schema or migration changes.',
  'related-docs: ../ops/migrations.md',
  '---',
  '',
  '# Data dictionary',
  '',
  '> Generated by `pnpm docs:data:generate`. Do not edit by hand.',
  '',
  'All owner-scoped tables use forced PostgreSQL row-level security through the transaction-local `meridian.user_id` setting. `schema_registry` and `edge_type_registry` are system-owned. No table is partitioned. WP-19 adds one variable-dimension pgvector column with no approximate vector index while provider/model selection remains inactive.',
  '',
];

for (const table of Object.values(schemaTables).sort((left, right) =>
  getTableName(left).localeCompare(getTableName(right)),
)) {
  const config = getTableConfig(table);
  lines.push(
    `## ${config.name}`,
    '',
    '| Column | SQL type | Null | Default | Primary |',
    '|---|---|---|---|---|',
  );
  for (const column of config.columns) {
    const defaultValue = column.hasDefault ? 'yes' : 'no';
    lines.push(
      `| \`${column.name}\` | \`${column.getSQLType()}\` | ${column.notNull ? 'no' : 'yes'} | ${defaultValue} | ${column.primary ? 'yes' : 'no'} |`,
    );
  }

  if (config.foreignKeys.length > 0) {
    lines.push('', 'Foreign keys:');
    for (const foreignKey of config.foreignKeys) {
      const reference = foreignKey.reference();
      lines.push(
        `- \`${foreignKey.getName()}\`: (${reference.columns.map((column) => column.name).join(', ')}) → \`${getTableName(reference.foreignTable)}\` (${reference.foreignColumns.map((column) => column.name).join(', ')})`,
      );
    }
  }

  const indexes = config.indexes
    .map((index) => index.config.name)
    .filter((name): name is string => typeof name === 'string');
  if (indexes.length > 0)
    lines.push(
      '',
      `Indexes: ${indexes.map((name) => `\`${name}\``).join(', ')}.`,
    );
  lines.push('');
}

lines.push(
  '## Custom migration controls',
  '',
  '- pgvector stores immutable, model-versioned Standard-only retrieval embeddings in one variable-dimension column. No HNSW/IVFFlat index exists before a model dimension and measured need are accepted.',
  '- `entries.current_revision_id` and `domain_events.aggregate_id` have owner-matching composite foreign keys added by custom migration.',
  '- Entry revisions, knowledge revisions/chunks/citations, retrieval embeddings, context manifests/items, and domain events reject updates; deletion remains available for governed hard-deletion propagation.',
  '- A database trigger rejects embeddings unless their exact owner-matching source is Standard, its content hash matches, and an external source is not deletion-pending.',
  '- Resource registry seeds include entries, proposals, tasks, reminders, agenda blocks, goals, knowledge sources, and knowledge claims.',
  '- Edge vocabulary seeds: `part_of`, `depends_on`, `blocks`, `conflicts_with`, `supports`, and `merged_into` at semantics version 1.',
  '',
);

const generated = `${lines.join('\n').trimEnd()}\n`;
if (process.argv.includes('--check')) {
  const existing = readFileSync(outputPath, 'utf8');
  if (existing !== generated) {
    console.error(
      'docs/domain/data-dictionary.md is stale. Run pnpm docs:data:generate.',
    );
    process.exit(1);
  }
  console.log('Generated data dictionary is current.');
} else {
  writeFileSync(outputPath, generated);
  console.log(`Generated ${outputPath}.`);
}
